### ISSUE TITLE
Validate different Value than type = cast error

### ISSUE THREAD

**Issue by mbenatti** [onboardingsystems/enum_type#4]
Giving a example (not complete) schema and enum: 

```Ruby
def MySchema do
  schema "myschema" do
     fields :operation, :string
     field :type, Type
  end
  
 defenum Type do
    value(Deposit, "DEPOSIT")
    value(Withdrawal, "WITHDRAWAL")
  end

  def changeset(my_schema // __MODULE__, params // %{})
    event
    |> cast(params, [:operation, :name])
    |> validate_required(@required)
    |> Type.validate(:type, message: "Invalid operation Type")
  end
end
```

Calling the changeset with `Type = "not_exist"` or event `Type: nil` will produce the following error on changeset:

```Ruby
MySchema.changeset(MySchema, %{name: "whatever", type: "not_exist" })
#or
MySchema.changeset(MySchema, %{name: "whatever", type: nil })

#Will produce something like this

     ** (CaseClauseError) no case clause matching: nil
     code: changeset = MySchema.changeset(%MySchema{}, params)
     stacktrace:
       (model) lib/model/my_schema.ex:46: 
Model.MySchema.validate_type/1
       (model) lib/model/trades/my_schema.ex:41: 
Model.MySchema.changeset/2
```

Looks like the `type`  cannot be cast to `MySchema.Type`  and on the `validate/2` function you not expect this: (the value empty on changes, as a `nil`)

```Ruby
changeset: #Ecto.Changeset<
  action: nil,
  changes: %{name: "my name"},
  errors: [
    type: {"is invalid",
     [type: MySchema.Type, validation: :cast]}
  ],
  data: #MySchema<>,
  valid?: false
>

```

Elixir 1.8.1
Erlang 21.3
Ecto 3.0

**Comment by brettv** [comment]
Sorry, somehow I never saw this issue come in.

When you call:

```
MySchema.changeset(MySchema, %{name: "whatever", type: "not_exist" })
```

You are passing in an atom as the first argument.  If you change it to a struct, it should work as expected:

```
MySchema.changeset(%MySchema{}, %{name: "whatever", type: "not_exist" })
```
